name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check code formatting
      uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 16

  build-and-test:
    needs: format-check
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtimageformats'

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=cl -DCMAKE_CXX_CLANG_TIDY="clang-tidy"

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      working-directory: build
      run: ctest -C Release --output-on-failure

    - name: Deploy Qt Dependencies
      run: |
        mkdir dist
        copy build\src\Release\ImageComparatorApp.exe dist\
        windeployqt --qmldir src dist\ImageComparatorApp.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ImageComparator-Release
        path: dist/
