name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtimageformats'

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=cl

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      working-directory: build
      run: ctest -C Release --output-on-failure

    - name: Deploy Qt Dependencies
      run: |
        mkdir dist
        copy build\src\Release\ImageComparator.exe dist\
        windeployqt --qmldir src dist\ImageComparator.exe

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'ImageComparator-Windows.zip'
        directory: 'dist'

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/ImageComparator-Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
